/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmBodega.java
 *
 * Created on 8/10/2012, 09:28:44 PM
 */
package ppal;

import java.awt.Color;
import java.awt.Component;
import java.util.List;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author John Bayron
 */
public class FrmBodega extends javax.swing.JFrame {
    
    List<ItemInventario> itemsInventario;
    Bodega bodega;
    
    public static final Color VERDE = new Color(0,153,0);    
    public static final Color ROJO = new Color(255,60,60);    
    public static final Color AMARILLO = new Color(255,222,0);
    public static final Color BASEAPP = new Color(102,102,102);
    public static final Color COMPONENTES=new Color(255, 255 , 255);

    /** Creates new form FrmBodega */
    public FrmBodega(Bodega bodega, List<ItemInventario> itemsInventario) {
        this.bodega=bodega;
        this.itemsInventario=itemsInventario;
        initComponents();
        
        tblInventario.setModel(new GeneralTableModel(itemsInventario, new String[] {"producto","cantidad","cantidadVirtual","precioVenta","reOrden","reCompra"}, new String[] {"Producto","Cant","C. Virtual","Precio","Reorden","Recompra"}, new Class[] {String.class, Integer.class,Integer.class, Long.class,Integer.class, Integer.class}));
        tblInventario.getColumnModel().getColumn(1).setPreferredWidth(40);
        tblInventario.getColumnModel().getColumn(1).setMaxWidth(40);
        tblInventario.getColumnModel().getColumn(2).setPreferredWidth(40);
        tblInventario.getColumnModel().getColumn(2).setMaxWidth(40);
        tblInventario.getColumnModel().getColumn(3).setPreferredWidth(45);
        tblInventario.getColumnModel().getColumn(3).setMaxWidth(45);
        tblInventario.getColumnModel().getColumn(4).setPreferredWidth(45);
        tblInventario.getColumnModel().getColumn(4).setMaxWidth(45);
        tblInventario.getColumnModel().getColumn(5).setPreferredWidth(45);
        tblInventario.getColumnModel().getColumn(5).setMaxWidth(45);                  
        tblInventario.revalidate();
        tblInventario.repaint();
    }
    
    public void refrescarInventario(){
        tblInventario.revalidate();
        tblInventario.repaint(); 
    }
    
    public void setMensajeInventario(String mensaje){
        txtMensajeInventario.setText(mensaje);        
    }
    
    public void setMensajeRecepcionEnvioPedidos(String mensaje){
        txtMensajeRecepcionEnvioPedidos.setText(mensaje);        
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBodega = new javax.swing.JPanel();
        PnlRecepcionEnvioPedidos = new javax.swing.JPanel();
        txtMensajeRecepcionEnvioPedidos = new javax.swing.JTextField();
        pnlInventario = new javax.swing.JPanel();
        txtMensajeInventario = new javax.swing.JTextField();
        scrInventario = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable(){
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column){
                Component returnComp = super.prepareRenderer(renderer, row,column);
                Integer cantidad= (Integer)getValueAt(row,1);
                Integer reOrden= (Integer)getValueAt(row,4);
                returnComp.setFont(new java.awt.Font("Tahoma", 1, 11));
                if( cantidad.intValue()==0 ){
                    returnComp.setBackground(FrmBodega.ROJO);
                    returnComp.setForeground(Color.WHITE);
                    return returnComp;
                }
                if ( cantidad.intValue()<reOrden.intValue() ){
                    returnComp.setBackground(FrmBodega.AMARILLO);
                    returnComp.setForeground(Color.BLACK);
                    return returnComp;
                }

                returnComp.setBackground(FrmBodega.VERDE);
                returnComp.setForeground(Color.WHITE);

                return returnComp;
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlBodega.setBackground(new java.awt.Color(255, 255, 255));

        PnlRecepcionEnvioPedidos.setBackground(FrmBodega.BASEAPP);
        PnlRecepcionEnvioPedidos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RECEPCIÓN Y ENVÍO DE PEDIDOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), java.awt.Color.white)); // NOI18N

        txtMensajeRecepcionEnvioPedidos.setBackground(FrmBodega.COMPONENTES);
        txtMensajeRecepcionEnvioPedidos.setEditable(false);
        txtMensajeRecepcionEnvioPedidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout PnlRecepcionEnvioPedidosLayout = new javax.swing.GroupLayout(PnlRecepcionEnvioPedidos);
        PnlRecepcionEnvioPedidos.setLayout(PnlRecepcionEnvioPedidosLayout);
        PnlRecepcionEnvioPedidosLayout.setHorizontalGroup(
            PnlRecepcionEnvioPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRecepcionEnvioPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMensajeRecepcionEnvioPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                .addContainerGap())
        );
        PnlRecepcionEnvioPedidosLayout.setVerticalGroup(
            PnlRecepcionEnvioPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRecepcionEnvioPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMensajeRecepcionEnvioPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlInventario.setBackground(FrmBodega.BASEAPP);
        pnlInventario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INVENTARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), java.awt.Color.white)); // NOI18N

        txtMensajeInventario.setBackground(FrmBodega.COMPONENTES);
        txtMensajeInventario.setEditable(false);
        txtMensajeInventario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tblInventario.setBackground(FrmBodega.COMPONENTES);
        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrInventario.setViewportView(tblInventario);

        javax.swing.GroupLayout pnlInventarioLayout = new javax.swing.GroupLayout(pnlInventario);
        pnlInventario.setLayout(pnlInventarioLayout);
        pnlInventarioLayout.setHorizontalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMensajeInventario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                    .addComponent(scrInventario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlInventarioLayout.setVerticalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventarioLayout.createSequentialGroup()
                .addComponent(txtMensajeInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlBodegaLayout = new javax.swing.GroupLayout(pnlBodega);
        pnlBodega.setLayout(pnlBodegaLayout);
        pnlBodegaLayout.setHorizontalGroup(
            pnlBodegaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodegaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBodegaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlInventario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PnlRecepcionEnvioPedidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlBodegaLayout.setVerticalGroup(
            pnlBodegaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodegaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnlRecepcionEnvioPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBodega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBodega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        bodega.desconectarOficinaCentral();
    }//GEN-LAST:event_formWindowClosing

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlRecepcionEnvioPedidos;
    private javax.swing.JPanel pnlBodega;
    private javax.swing.JPanel pnlInventario;
    private javax.swing.JScrollPane scrInventario;
    private javax.swing.JTable tblInventario;
    private javax.swing.JTextField txtMensajeInventario;
    private javax.swing.JTextField txtMensajeRecepcionEnvioPedidos;
    // End of variables declaration//GEN-END:variables
}
