/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmSupermercado.java
 *
 * Created on 1/10/20100, 02:47:37 PM
 */

package ppal;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Usuario UTP
 */
public class FrmSupermercado extends javax.swing.JFrame {    
    private List<ItemInventario> itemsInventario;

    Supermercado supermercado;
       
    public static final Color VERDE = new Color(0,153,0);    
    public static final Color ROJO = new Color(255,60,60);    
    public static final Color AMARILLO = new Color(255,222,0);
    public static final Color BASEAPP = new Color(102,102,102);
    public static final Color COMPONENTES=new Color(255, 255 , 255);
    
    DlgPedirNombre dlgPedirNombre=new DlgPedirNombre(this, true, "Digitar nombre de supermercado");
    
    
    /** Creates new form FrmSupermercado */
    public FrmSupermercado(Supermercado supermercado, List<ItemInventario> itemsInventario ) {
        this.supermercado=supermercado;
        this.itemsInventario=itemsInventario;
        
        initComponents();

        tbItemsMercado.setModel(new GeneralTableModel(null, new String[] {"producto","cantidad"}, new String[] {"Producto","Cant"}, new Class[] {String.class, Integer.class}));
        tbItemsMercado.getColumnModel().getColumn(1).setPreferredWidth(35);
        tbItemsMercado.getColumnModel().getColumn(1).setMaxWidth(35);
    
        tblInventario.setModel(new GeneralTableModel(itemsInventario, new String[] {"producto","cantidad","cantidadVirtual","precioVenta","reOrden","reCompra"}, new String[] {"Producto","Cant","C. Virtual","Precio","Reorden","Recompra"}, new Class[] {String.class, Integer.class,Integer.class, Long.class,Integer.class, Integer.class}));
        tblInventario.getColumnModel().getColumn(1).setPreferredWidth(40);
        tblInventario.getColumnModel().getColumn(1).setMaxWidth(40);
        tblInventario.getColumnModel().getColumn(2).setPreferredWidth(40);
        tblInventario.getColumnModel().getColumn(2).setMaxWidth(40);
        tblInventario.getColumnModel().getColumn(3).setPreferredWidth(45);
        tblInventario.getColumnModel().getColumn(3).setMaxWidth(45);
        tblInventario.getColumnModel().getColumn(4).setPreferredWidth(45);
        tblInventario.getColumnModel().getColumn(4).setMaxWidth(45);
        tblInventario.getColumnModel().getColumn(5).setPreferredWidth(45);
        tblInventario.getColumnModel().getColumn(5).setMaxWidth(45);                  
        tblInventario.revalidate();
        tblInventario.repaint();
        
        
    }
    
    public void mostrarMensajeError(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Supermercado", JOptionPane.ERROR_MESSAGE);
    }
    
    /*public static void mostrarMensajeError(String titulo, String mensaje){
        JOptionPane.showMessageDialog(new JFrame(), mensaje, titulo, JOptionPane.ERROR_MESSAGE);
    }*/
    
    public String mostrarDialogoObtenerNombre(){
        dlgPedirNombre.setLocationRelativeTo(null);
        dlgPedirNombre.setVisible(true);
        if (dlgPedirNombre.isAceptado())
            return dlgPedirNombre.getNombre();
        System.exit(0); 
        return null;
    }
    
    
    
    /*@Override
    public void setVisible(boolean ban){
        super.setVisible(ban);
        dlgPedirNombre.setLocationRelativeTo(null);
        supermercado.setNombre(dlgPedirNombre.getNombre());
        this.setTitle(supermercado.getNombre());
        
    }*/

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSupermercado = new javax.swing.JPanel();
        scrCajas = new javax.swing.JScrollPane();
        pnlCajas = new javax.swing.JPanel();
        pnlAsignadorMercados = new javax.swing.JPanel();
        txtMensajeAsignadorMercados = new javax.swing.JTextField();
        pnlMonitorCajas = new javax.swing.JPanel();
        txtMensajeMonitorCajas = new javax.swing.JTextField();
        PnlMonitorInventario = new javax.swing.JPanel();
        txtMensajeMonitorInventario = new javax.swing.JTextField();
        pnlContenedorFabricaMercados = new javax.swing.JPanel();
        pnlFabricaMercados = new javax.swing.JPanel();
        scrItemsMercado = new javax.swing.JScrollPane();
        tbItemsMercado = new javax.swing.JTable(){
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column){
                Component returnComp = super.prepareRenderer(renderer, row,column);
                returnComp.setFont(new java.awt.Font("Tahoma", 1, 11));
                return returnComp;
            }
        };
        lblCantidadProductos = new javax.swing.JLabel();
        txtCantidadProductos = new javax.swing.JTextField();
        btnStopFabrica = new javax.swing.JButton();
        txtMensajeFabrica = new javax.swing.JTextField();
        txtMensajeMercado = new javax.swing.JTextField();
        lblMercado = new javax.swing.JLabel();
        txtMercado = new javax.swing.JTextField();
        pnlInventario = new javax.swing.JPanel();
        txtMensajeInventario = new javax.swing.JTextField();
        scrInventario = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable(){
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column){
                Component returnComp = super.prepareRenderer(renderer, row,column);
                Integer cantidad= (Integer)getValueAt(row,1);
                Integer reOrden= (Integer)getValueAt(row,4);
                returnComp.setFont(new java.awt.Font("Tahoma", 1, 11));
                if( cantidad.intValue()==0 ){
                    returnComp.setBackground(FrmSupermercado.ROJO);
                    returnComp.setForeground(Color.WHITE);
                    return returnComp;
                }
                if ( cantidad.intValue()<reOrden.intValue() ){
                    returnComp.setBackground(FrmSupermercado.AMARILLO);
                    returnComp.setForeground(Color.BLACK);
                    return returnComp;
                }

                returnComp.setBackground(FrmSupermercado.VERDE);
                returnComp.setForeground(Color.WHITE);

                return returnComp;
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(supermercado.getNombre());
        setBackground(new java.awt.Color(0, 0, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlSupermercado.setBackground(new java.awt.Color(255, 255, 255));

        pnlCajas.setBackground(FrmSupermercado.BASEAPP);
        pnlCajas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CAJAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlCajas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 13, 5));
        scrCajas.setViewportView(pnlCajas);

        pnlAsignadorMercados.setBackground(FrmSupermercado.BASEAPP);
        pnlAsignadorMercados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ASIGNADOR DE MERCADOS A CAJAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), java.awt.Color.white)); // NOI18N

        txtMensajeAsignadorMercados.setBackground(FrmSupermercado.COMPONENTES);
        txtMensajeAsignadorMercados.setEditable(false);
        txtMensajeAsignadorMercados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnlAsignadorMercadosLayout = new javax.swing.GroupLayout(pnlAsignadorMercados);
        pnlAsignadorMercados.setLayout(pnlAsignadorMercadosLayout);
        pnlAsignadorMercadosLayout.setHorizontalGroup(
            pnlAsignadorMercadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsignadorMercadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMensajeAsignadorMercados, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAsignadorMercadosLayout.setVerticalGroup(
            pnlAsignadorMercadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsignadorMercadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMensajeAsignadorMercados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMonitorCajas.setBackground(FrmSupermercado.BASEAPP);
        pnlMonitorCajas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MONITOR DE CAJAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), java.awt.Color.white)); // NOI18N

        txtMensajeMonitorCajas.setBackground(FrmSupermercado.COMPONENTES);
        txtMensajeMonitorCajas.setEditable(false);
        txtMensajeMonitorCajas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnlMonitorCajasLayout = new javax.swing.GroupLayout(pnlMonitorCajas);
        pnlMonitorCajas.setLayout(pnlMonitorCajasLayout);
        pnlMonitorCajasLayout.setHorizontalGroup(
            pnlMonitorCajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMonitorCajasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMensajeMonitorCajas)
                .addContainerGap())
        );
        pnlMonitorCajasLayout.setVerticalGroup(
            pnlMonitorCajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMonitorCajasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMensajeMonitorCajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PnlMonitorInventario.setBackground(FrmSupermercado.BASEAPP);
        PnlMonitorInventario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MONITOR DE INVENTARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), java.awt.Color.white)); // NOI18N

        txtMensajeMonitorInventario.setBackground(FrmSupermercado.COMPONENTES);
        txtMensajeMonitorInventario.setEditable(false);
        txtMensajeMonitorInventario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout PnlMonitorInventarioLayout = new javax.swing.GroupLayout(PnlMonitorInventario);
        PnlMonitorInventario.setLayout(PnlMonitorInventarioLayout);
        PnlMonitorInventarioLayout.setHorizontalGroup(
            PnlMonitorInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMonitorInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMensajeMonitorInventario)
                .addContainerGap())
        );
        PnlMonitorInventarioLayout.setVerticalGroup(
            PnlMonitorInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMonitorInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMensajeMonitorInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlContenedorFabricaMercados.setBackground(FrmSupermercado.BASEAPP);
        pnlContenedorFabricaMercados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FÁBRICA DE MERCADOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), java.awt.Color.white)); // NOI18N

        tbItemsMercado.setBackground(FrmSupermercado.COMPONENTES);
        scrItemsMercado.setViewportView(tbItemsMercado);

        lblCantidadProductos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCantidadProductos.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidadProductos.setText("Cant. productos tentativos");

        txtCantidadProductos.setBackground(FrmSupermercado.COMPONENTES);
        txtCantidadProductos.setEditable(false);
        txtCantidadProductos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCantidadProductos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnStopFabrica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/16.png"))); // NOI18N
        btnStopFabrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopFabricaActionPerformed(evt);
            }
        });

        txtMensajeFabrica.setBackground(FrmSupermercado.COMPONENTES);
        txtMensajeFabrica.setEditable(false);
        txtMensajeFabrica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtMensajeMercado.setBackground(FrmSupermercado.COMPONENTES);
        txtMensajeMercado.setEditable(false);
        txtMensajeMercado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        lblMercado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMercado.setForeground(new java.awt.Color(255, 255, 255));
        lblMercado.setText("Mercado");

        txtMercado.setBackground(FrmSupermercado.COMPONENTES);
        txtMercado.setEditable(false);
        txtMercado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout pnlFabricaMercadosLayout = new javax.swing.GroupLayout(pnlFabricaMercados);
        pnlFabricaMercados.setLayout(pnlFabricaMercadosLayout);
        pnlFabricaMercadosLayout.setHorizontalGroup(
            pnlFabricaMercadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFabricaMercadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFabricaMercadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrItemsMercado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addGroup(pnlFabricaMercadosLayout.createSequentialGroup()
                        .addComponent(txtMensajeFabrica, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStopFabrica, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFabricaMercadosLayout.createSequentialGroup()
                        .addComponent(lblMercado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMercado, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCantidadProductos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMensajeMercado, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlFabricaMercadosLayout.setVerticalGroup(
            pnlFabricaMercadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFabricaMercadosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlFabricaMercadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMensajeFabrica, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStopFabrica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFabricaMercadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFabricaMercadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMercado)
                        .addComponent(txtMercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFabricaMercadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCantidadProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCantidadProductos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMensajeMercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrItemsMercado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlFabricaMercadosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCantidadProductos, txtMensajeFabrica});

        javax.swing.GroupLayout pnlContenedorFabricaMercadosLayout = new javax.swing.GroupLayout(pnlContenedorFabricaMercados);
        pnlContenedorFabricaMercados.setLayout(pnlContenedorFabricaMercadosLayout);
        pnlContenedorFabricaMercadosLayout.setHorizontalGroup(
            pnlContenedorFabricaMercadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorFabricaMercadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFabricaMercados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContenedorFabricaMercadosLayout.setVerticalGroup(
            pnlContenedorFabricaMercadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorFabricaMercadosLayout.createSequentialGroup()
                .addComponent(pnlFabricaMercados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlInventario.setBackground(FrmSupermercado.BASEAPP);
        pnlInventario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INVENTARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), java.awt.Color.white)); // NOI18N

        txtMensajeInventario.setBackground(FrmSupermercado.COMPONENTES);
        txtMensajeInventario.setEditable(false);
        txtMensajeInventario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tblInventario.setBackground(FrmSupermercado.COMPONENTES);
        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrInventario.setViewportView(tblInventario);

        javax.swing.GroupLayout pnlInventarioLayout = new javax.swing.GroupLayout(pnlInventario);
        pnlInventario.setLayout(pnlInventarioLayout);
        pnlInventarioLayout.setHorizontalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMensajeInventario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                    .addComponent(scrInventario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlInventarioLayout.setVerticalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventarioLayout.createSequentialGroup()
                .addComponent(txtMensajeInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlSupermercadoLayout = new javax.swing.GroupLayout(pnlSupermercado);
        pnlSupermercado.setLayout(pnlSupermercadoLayout);
        pnlSupermercadoLayout.setHorizontalGroup(
            pnlSupermercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSupermercadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSupermercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrCajas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1255, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSupermercadoLayout.createSequentialGroup()
                        .addComponent(pnlContenedorFabricaMercados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSupermercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PnlMonitorInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlMonitorCajas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlAsignadorMercados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlSupermercadoLayout.setVerticalGroup(
            pnlSupermercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSupermercadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSupermercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSupermercadoLayout.createSequentialGroup()
                        .addComponent(pnlAsignadorMercados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMonitorCajas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PnlMonitorInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContenedorFabricaMercados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(scrCajas, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSupermercado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSupermercado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopFabricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopFabricaActionPerformed
        // TODO add your handling code here:        
        if (pnlFabricaMercados.getBackground().equals(FrmSupermercado.VERDE)){
            txtMensajeFabrica.setText("Fábrica en proceso de cierre");
            pnlFabricaMercados.setBackground(FrmSupermercado.ROJO);
        }
        else{
            txtMensajeFabrica.setText("Fábrica en proceso de reapertura");
            pnlFabricaMercados.setBackground(FrmSupermercado.VERDE);
        }        
        supermercado.activarInactivarFabrica();
    }//GEN-LAST:event_btnStopFabricaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        supermercado.desconectarOficinaCentral();
    }//GEN-LAST:event_formWindowClosing

    public void addCaja(PnlCaja caja){
        pnlCajas.add(caja);
    }
        
    public void setColorFabricaMercados(Color color){
        pnlFabricaMercados.setBackground(color);
    }
        
    public void finalizarGeneracionMercado(String nombre, int numItemsMercado){
         if (numItemsMercado==0){
            txtMensajeFabrica.setText(nombre+" sin items por falta de inventario");
         }
         else{
            txtMensajeFabrica.setText("Finalización "+nombre);
         }
    }
    
    public void iniciarGeneracionMercado(String nombre, int numProductos, List<ItemMercado> itemsMercado){
         txtMensajeFabrica.setText("Generación "+nombre);
         txtMercado.setText(nombre);
         txtCantidadProductos.setText(""+numProductos);
         ((GeneralTableModel)tbItemsMercado.getModel()).setDatos(itemsMercado);
         tbItemsMercado.revalidate();
         tbItemsMercado.repaint();
    }

    public void actualizarItemMercado(int seleccion,String mensaje){
        txtMensajeMercado.setText(mensaje);
        tbItemsMercado.getSelectionModel().setSelectionInterval(seleccion, seleccion);
        tbItemsMercado.revalidate();
        tbItemsMercado.repaint();
    }
    
    public void limpiarFabrica(){
        txtMensajeMercado.setText("");
        txtMercado.setText("");
        txtCantidadProductos.setText("");
        ((GeneralTableModel)tbItemsMercado.getModel()).setDatos(new ArrayList());
        tbItemsMercado.revalidate();
        tbItemsMercado.repaint();
    }
    
    public void pararFabrica(){
        txtMensajeFabrica.setText("Fábrica parada ");
    }
    
    public void setTextoMercado(String mensaje){
        txtMercado.setText(mensaje);        
    }
    
    public void setTextoCantidadProductos(String mensaje){
        txtCantidadProductos.setText(mensaje);        
    }
    
    public void setMensajeFabrica(String mensaje){
        txtMensajeFabrica.setText(mensaje);        
    } 
         
    public void setMensajeInventario(String mensaje){
        txtMensajeInventario.setText(mensaje);        
    }  
    
    public void setMensajeAsignador(String mensaje){
        txtMensajeAsignadorMercados.setText(mensaje);
    }

    public void setMensajeMonitorCajas(String mensaje){
        txtMensajeMonitorCajas.setText(mensaje);
    }

    public void setMensajeMonitorInventario(String mensaje){
        txtMensajeMonitorInventario.setText(mensaje);
    }
    
    public void setMensajeMercado(String mensaje){
        txtMensajeMercado.setText(mensaje);
    }
    
    public void refrescarInventario(){
        tblInventario.revalidate();
        tblInventario.repaint(); 
    }
    
    public void refrescarItemsMercado(){
        tbItemsMercado.revalidate();
        tbItemsMercado.repaint(); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlMonitorInventario;
    private javax.swing.JButton btnStopFabrica;
    private javax.swing.JLabel lblCantidadProductos;
    private javax.swing.JLabel lblMercado;
    private javax.swing.JPanel pnlAsignadorMercados;
    private javax.swing.JPanel pnlCajas;
    private javax.swing.JPanel pnlContenedorFabricaMercados;
    private javax.swing.JPanel pnlFabricaMercados;
    private javax.swing.JPanel pnlInventario;
    private javax.swing.JPanel pnlMonitorCajas;
    private javax.swing.JPanel pnlSupermercado;
    private javax.swing.JScrollPane scrCajas;
    private javax.swing.JScrollPane scrInventario;
    private javax.swing.JScrollPane scrItemsMercado;
    private javax.swing.JTable tbItemsMercado;
    private javax.swing.JTable tblInventario;
    private javax.swing.JTextField txtCantidadProductos;
    private javax.swing.JTextField txtMensajeAsignadorMercados;
    private javax.swing.JTextField txtMensajeFabrica;
    private javax.swing.JTextField txtMensajeInventario;
    private javax.swing.JTextField txtMensajeMercado;
    private javax.swing.JTextField txtMensajeMonitorCajas;
    private javax.swing.JTextField txtMensajeMonitorInventario;
    private javax.swing.JTextField txtMercado;
    // End of variables declaration//GEN-END:variables


}
