/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlCaja.java
 *
 * Created on 1/10/2012, 08:10:37 PM
 */
package ppal;

import java.awt.Color;
import java.awt.Component;
import java.util.List;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author John Bayron
 */
public class PnlCaja extends javax.swing.JPanel {

    private String nombre;
    
    /** Creates new form PnlCaja */
    public PnlCaja(String nombre,List<ItemMovCaja> itemsMovCaja, List<Mercado> cola) {
        this.nombre = nombre;       
        initComponents();
        tblCola.setModel(new GeneralTableModel(cola, new String[] {"nombre"}, new String[] {"Mercado"}, new Class[] {String.class}));
        tblProductos.setModel(new GeneralTableModel(itemsMovCaja, new String[] {"producto","cantidad","valorUnitario","subtotal"}, new String[] {"Producto","Cant","V. unit","Subtotal"}, new Class[] {String.class,String.class,String.class,String.class}));
        tblProductos.getColumnModel().getColumn(1).setPreferredWidth(30);
        tblProductos.getColumnModel().getColumn(1).setMaxWidth(30);
        tblProductos.getColumnModel().getColumn(2).setPreferredWidth(35);
        tblProductos.getColumnModel().getColumn(2).setMaxWidth(35);
        tblProductos.getColumnModel().getColumn(3).setPreferredWidth(40);
        tblProductos.getColumnModel().getColumn(3).setMaxWidth(40);
        txtNumMercados.setText("0");
    }
      
    public void actualizarCola(int tamano){
        tblCola.revalidate();
        tblCola.repaint();
        txtNumMercados.setText(""+tamano);
    }
    
    public void limpiar(){
        txtProducto.setText("");
        txtCantidad.setText("");
        txtValorUnitario.setText("");
        txtSubtotal.setText("");
        txtTotal.setText("");
        tblProductos.revalidate();
        tblProductos.repaint();
    }

    public void mostrarItemActual (Producto producto, int cantidad, long valorUnitario, long subtotal, long total, int indSel ){
        txtProducto.setText(producto.toString());
        txtCantidad.setText(""+cantidad);
        txtValorUnitario.setText(""+valorUnitario);
        txtSubtotal.setText(""+subtotal);
        txtTotal.setText(""+total);
        tblProductos.getSelectionModel().setSelectionInterval(indSel, indSel);
        tblProductos.revalidate();
        tblProductos.repaint();
    }
    
    public void setColorCaja(Color color){
        this.setBackground(color);
        pnlCola.setBackground(color);
        pnlItemActual.setBackground(color);
        pnlMercadoActual.setBackground(color);
        pnlItemsMovCaja.setBackground(color);
    }
    
    public void setMensaje(String mensaje){
        txtMensaje.setText(mensaje);
    }
    
    public void refrescarProductos(String mensaje){
        tblProductos.revalidate();
        tblProductos.repaint();
    }
    
    public void refrescarCola(){
        tblCola.revalidate();
        tblCola.repaint();
    }    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMensaje = new javax.swing.JTextField();
        pnlCola = new javax.swing.JPanel();
        scrCola = new javax.swing.JScrollPane();
        tblCola = new javax.swing.JTable(){
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column){
                Component returnComp = super.prepareRenderer(renderer, row,column);
                returnComp.setFont(new java.awt.Font("Tahoma", 1, 11));
                return returnComp;
            }
        };
        lblNumMercados = new javax.swing.JLabel();
        txtNumMercados = new javax.swing.JTextField();
        pnlMercadoActual = new javax.swing.JPanel();
        pnlItemActual = new javax.swing.JPanel();
        lblProducto = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblValorUnitario = new javax.swing.JLabel();
        txtValorUnitario = new javax.swing.JTextField();
        lblSubtotal = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        pnlItemsMovCaja = new javax.swing.JPanel();
        scrProductos = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable(){
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column){
                Component returnComp = super.prepareRenderer(renderer, row,column);
                returnComp.setFont(new java.awt.Font("Tahoma", 1, 11));
                return returnComp;
            }
        };
        txtTotal = new javax.swing.JTextField();

        setBackground(FrmSupermercado.ROJO);
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, nombre.toUpperCase(), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        txtMensaje.setBackground(FrmSupermercado.COMPONENTES);
        txtMensaje.setEditable(false);
        txtMensaje.setFont(new java.awt.Font("Tahoma", 1, 12));

        pnlCola.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cola de mercados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), java.awt.Color.white)); // NOI18N

        tblCola.setBackground(FrmSupermercado.COMPONENTES);
        scrCola.setViewportView(tblCola);

        lblNumMercados.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblNumMercados.setForeground(new java.awt.Color(255, 255, 255));
        lblNumMercados.setText("# mercados");

        txtNumMercados.setBackground(FrmSupermercado.COMPONENTES);
        txtNumMercados.setEditable(false);
        txtNumMercados.setFont(new java.awt.Font("Tahoma", 1, 11));
        txtNumMercados.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout pnlColaLayout = new javax.swing.GroupLayout(pnlCola);
        pnlCola.setLayout(pnlColaLayout);
        pnlColaLayout.setHorizontalGroup(
            pnlColaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColaLayout.createSequentialGroup()
                .addGroup(pnlColaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlColaLayout.createSequentialGroup()
                        .addComponent(lblNumMercados, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumMercados, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlColaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(scrCola, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlColaLayout.setVerticalGroup(
            pnlColaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlColaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumMercados)
                    .addComponent(txtNumMercados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrCola, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMercadoActual.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Mercado actual", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), java.awt.Color.white)); // NOI18N

        pnlItemActual.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Item actual", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), java.awt.Color.white)); // NOI18N

        lblProducto.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblProducto.setText("Producto");

        txtProducto.setBackground(FrmSupermercado.COMPONENTES);
        txtProducto.setEditable(false);
        txtProducto.setFont(new java.awt.Font("Tahoma", 1, 11));

        lblCantidad.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad.setText("Cantidad");

        txtCantidad.setBackground(FrmSupermercado.COMPONENTES);
        txtCantidad.setEditable(false);
        txtCantidad.setFont(new java.awt.Font("Tahoma", 1, 11));
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblValorUnitario.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblValorUnitario.setForeground(new java.awt.Color(255, 255, 255));
        lblValorUnitario.setText("V. unitario $");

        txtValorUnitario.setBackground(FrmSupermercado.COMPONENTES);
        txtValorUnitario.setEditable(false);
        txtValorUnitario.setFont(new java.awt.Font("Tahoma", 1, 11));
        txtValorUnitario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblSubtotal.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblSubtotal.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtotal.setText("Subtotal  $");

        txtSubtotal.setBackground(FrmSupermercado.COMPONENTES);
        txtSubtotal.setEditable(false);
        txtSubtotal.setFont(new java.awt.Font("Tahoma", 1, 11));
        txtSubtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout pnlItemActualLayout = new javax.swing.GroupLayout(pnlItemActual);
        pnlItemActual.setLayout(pnlItemActualLayout);
        pnlItemActualLayout.setHorizontalGroup(
            pnlItemActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItemActualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlItemActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlItemActualLayout.createSequentialGroup()
                        .addComponent(lblProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                    .addGroup(pnlItemActualLayout.createSequentialGroup()
                        .addGroup(pnlItemActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantidad)
                            .addComponent(lblValorUnitario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlItemActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorUnitario, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                    .addGroup(pnlItemActualLayout.createSequentialGroup()
                        .addComponent(lblSubtotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlItemActualLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCantidad, lblProducto, lblSubtotal, lblValorUnitario});

        pnlItemActualLayout.setVerticalGroup(
            pnlItemActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItemActualLayout.createSequentialGroup()
                .addGroup(pnlItemActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlItemActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlItemActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorUnitario)
                    .addComponent(txtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlItemActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotal)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total  $ ");

        pnlItemsMovCaja.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos registrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), java.awt.Color.white)); // NOI18N

        tblProductos.setBackground(FrmSupermercado.COMPONENTES);
        scrProductos.setViewportView(tblProductos);

        javax.swing.GroupLayout pnlItemsMovCajaLayout = new javax.swing.GroupLayout(pnlItemsMovCaja);
        pnlItemsMovCaja.setLayout(pnlItemsMovCajaLayout);
        pnlItemsMovCajaLayout.setHorizontalGroup(
            pnlItemsMovCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
        );
        pnlItemsMovCajaLayout.setVerticalGroup(
            pnlItemsMovCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
        );

        txtTotal.setBackground(FrmSupermercado.COMPONENTES);
        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout pnlMercadoActualLayout = new javax.swing.GroupLayout(pnlMercadoActual);
        pnlMercadoActual.setLayout(pnlMercadoActualLayout);
        pnlMercadoActualLayout.setHorizontalGroup(
            pnlMercadoActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlItemActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMercadoActualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotal)
                .addGap(35, 35, 35)
                .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlItemsMovCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMercadoActualLayout.setVerticalGroup(
            pnlMercadoActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMercadoActualLayout.createSequentialGroup()
                .addComponent(pnlItemActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlItemsMovCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMercadoActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlMercadoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMercadoActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblNumMercados;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblValorUnitario;
    private javax.swing.JPanel pnlCola;
    private javax.swing.JPanel pnlItemActual;
    private javax.swing.JPanel pnlItemsMovCaja;
    private javax.swing.JPanel pnlMercadoActual;
    private javax.swing.JScrollPane scrCola;
    private javax.swing.JScrollPane scrProductos;
    private javax.swing.JTable tblCola;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtMensaje;
    private javax.swing.JTextField txtNumMercados;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtValorUnitario;
    // End of variables declaration//GEN-END:variables

}
